### ISSUE TITLE
missing SL calculations on figshare

### ISSUE THREAD

**Issue by ThomasGro** [xushiabbvie/TCGADEPMAP#1]
Thank you for providing the code and also results of your analyses. I found that your SL calculations on figshare https://figshare.com/projects/TCGADEPMAP_Mapping_Translational_Dependencies_and_Synthetic_Lethalities_within_The_Cancer_Genome_Atlas/130193 is empty (looping back to the publication folder). Could you please check.

**Comment by xushiabbvie** [comment]
Hi, thank you for your interest in our research. I just check the link and the supplemental data are there. Please double check.

**Comment by ThomasGro** [comment]
Thank you for your reply. 

However, I cannot see the R object file that is described in the paper: “…Lasso regression
analysis of gene essentiality profiles and 25,026 LOF events detected
in TCGADEPMAP yielded 633,232 synthetic lethal candidates (FDR < 0.01)
(all candidates added as an R object to a figshare repository), ...”

Maybe it does not show up in figshare?

This folder is empty: "project: TCGADEPMAP – Mapping Translational Dependencies and Synthetic Lethalities within The Cancer Genome Atlas"
![image](https://github.com/user-attachments/assets/852b23ed-3174-4c22-9a66-7d85a4c7ec0c)

**Comment by xushiabbvie** [comment]
I am not sure about the issue since I am able to see the data without login. Please check the SL data through this link. Hope this helps. Thanks. https://figshare.com/s/a76d338a425273b42c8b

**Comment by ThomasGro** [comment]
Yes, this link works for me. I can see the .rds files.
