### ISSUE TITLE
[run_expression_alignment_TCGADEPMAP.R] Error in `ScaleData()`

### ISSUE THREAD

**Issue by aambioinfo** [xushiabbvie/TCGADEPMAP#3]
Hello again, 

when running `TCGA_obj <- create_Seurat_object(dat$TCGA_mat, dat$TCGA_ann, type='tumor')` I got this `Error in ScaleData()`:
![image](https://github.com/user-attachments/assets/fdc57b91-7e32-4394-bf77-56d77948310b)

We added this line (122) of code to `src/Celligner_methods.R` and it seems to solve the problem: 
![image](https://github.com/user-attachments/assets/d1c59564-8c4b-4586-aa05-178f9f131dc8)

Is this the correct way to prevent the error from triggering?

Many thanks.

**Comment by xushiabbvie** [comment]
Hi, we already reference the src/Celligner_methods.R in the script at line 10 'source("src/Celligner_methods.R")'. This line will run src/Celligner_methods.R for you. It seems that you skip this line or getting errors running this. You can either run this line or run src/Celligner_methods.R yourself. Thanks.

**Comment by aambioinfo** [comment]
Hi, yes, I run all the lines in the `run_expression_alignment_TCGADEPMAP.R`, including the `source("src/Celligner_methods.R")` and I got that error, but after adding `seu_obj <- Seurat::NormalizeData(seu_obj)` in line 122 in `src/Celligner_methods.R`, the problem was solved. My question was if this line should be added to the original code to solve the issue. Thanks.

**Comment by xushiabbvie** [comment]
No, if you run source("src/Celligner_methods.R"), then every line in source("src/Celligner_methods.R") should be executed already.

**Comment by ajaybabu27** [comment]
@xushiabbvie, @aambioinfo was right. You need to add `seu_obj <- Seurat::NormalizeData(seu_obj)` in line 122 in `src/Celligner_methods.R` for `run_expression_alignment_TCGADEPMAP.R` code to work without errors. As @aambioinfo asked is this a right of line of code to add or did you have something else on your end ?

**Comment by xushiabbvie** [comment]
Hi @ajaybabu27 and @aambioinfo , thank you for trying our code. I did test on my end but it works with no errors. I think this may be related to newer Seurat version. Can you let me know which version are you using?

**Comment by ajaybabu27** [comment]
The version I am using is `Seurat_5.0.1`

**Comment by aambioinfo** [comment]
The version I am using is `Seurat 5.1.0`

**Comment by xushiabbvie** [comment]
I think the error comes from Seurat v5. The version I am using is Seurat 4.4.0. If you would like to use Seurat v5 for this analysis, you can add the line @aambioinfo suggested. Thank you for checking out!

**Comment by ajaybabu27** [comment]
Thanks for your inputs @xushiabbvie. I was able to recreate your TCGA dependency prediction results after using Seurat 4.4.0. Using the Seurat 5.0.1 results in slightly different TCGA dependency prediction results from your original results (pearson correlation to your published results in the manuscript was 0.85).

**Comment by szalata** [comment]
I have run it with Seurat 5.0.1 and got 0.85 Pearson correlation, but after downgrading to 4.4.0, I still get 0.85 correlation, where the correlation between my two runs is ~0.99. I assume it might be an issue with some other dependencies. Could you please provide an environment for reproducibility @xushiabbvie ?
